const fs  = require('fs')
const settings = require('../settings.json')
const discord  = require('discord.js')
client = new discord.Client()
module.exports = {
  run: async message => {
    const filename ='./alt.txt'/**The name of your txt file */
    fs.readFile(filename, "utf-8", function(err, data){
      if(err) {
          throw err;
      }
      try{
      var lines = data.split('\n');
      var line = lines[0]
      var account = line.split(":")
      fs.writeFile(filename, lines.slice(1).join('\n'), function(err) {
        if(err) throw err;
    });
      message.author.send(new discord.MessageEmbed().setDescription('Ton compte à été généré.').addFields({	
        name: "Username/Email",	
        value: account[0]
      },{	
        name: "Password",
        value: account[1]
      }).setColor('#'+Math.floor(Math.random()* (70000 - 0) + 0)).setTimestamp().setFooter('Developped by Okone#0667 in js - github.com/wOkone').setAuthor('Generator'/**Type here the name of your sever */, message.guild.iconURL({dynamic:true})))
    message.channel.send(new discord.MessageEmbed().setAuthor('Generator').setDescription(`${message.author} Your account as been send in your private message`))
  }catch(e){
    message.channel.send(new discord.MessageEmbed().setAuthor('Generator').setDescription(`${message.author} We don't have stock, please contact an administrator of the server`))
    console.log(e)}})
    if(settings.log == 'off') return
    else{
      try{
      let channelid = message.guild.channels.cache.get(settings.log)
      try{
      channelid.send(new discord.MessageEmbed().setAuthor('Log').setDescription(`An account as been generated by ${message.author}`))
    }catch(e){return console.log(e)}}catch{}}
},
name: "generate"
}